services:
  backend-node:
    build: ./backend-node
    container_name: uao_eats_node
    ports:
      - "3000:3000"
    env_file:
      - ./backend-node/.env
    depends_on:
      backend-analytics:
        condition: service_healthy
    networks:
      - uao_net
    restart: unless-stopped

  backend-analytics:
    build: ./backend-analytics
    container_name: uao_eats_analytics
    ports:
      - "8001:8001"
    env_file:
      - ./backend-analytics/.env
    networks:
      - uao_net
    restart: unless-stopped

networks:
  uao_net:
    driver: bridge
